name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "055524399ac12b8e7023a353245cdaec0dde63642500fa46af1a089d6ec8754a"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
