name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e63e5c0987d4894971a91f10901a3ddae8db0da57054e8dff184dd534d2b6c52"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
