name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fce9bbb6c15c9c17e76830086b58fe5b2f4c1ce5488c5ec9d1304b5f871422e5"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
