name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88f81c6d92fe563c9c590fe2e0de7a18b66c1b067b06ac290556f4be910f86d0"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
