name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "635224c766fc0750e7e6671f7d4c05d3ad71badc9d4035d550796aca600ba502"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
