name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0528d5717df800a51ba096b63b998b4c6a1a0841344fdc70e11dd9e0c51f42c7"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
