name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f84b225211e10e378ea654ae2557064bfada742ab57f8da453f215fa817ebea"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
