name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "928862e3e70acbb2d9b2c37285c09e5c63266976d3eebc3f8dd0256784b5ecd4"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
