name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3694a0575645c4e9f2af7335944f16c8b2685ffd167e5a59f1b30cd191ea1b1c"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
