name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8e99b82373a9cb783950aeeaf288e29f8d4d0e70e76a4d1af32e6364e60b9cf8"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
