name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20ebd3c02c90b2c67afc7100168bc11a3bc09db547bdcbb20aae37c1f1b6cfdf"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
