name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1499ab088b5e9b4feab08e092a5d00d4dc7e5a33c3ae5dcc5bc1c488dcf87a94"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
