name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c65a1b7cf416d4c9c227ec187650452bd306d7e1c9cc0a6184fc8a7094e9a08e"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
