name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1d2f510820d01bdd182f74e21d332e2cf83c3355a7235536f66cf7d9daa5dbc7"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
