name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f0d71fe41dcff14bec092231bd6239d4630ef2606a637cbb0c96cefd16a725cb"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
