name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d7c99a72b77c06d7863500ca7957c7eb6a2b935c44c91b59f7b007aabb7dfccf"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
