name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6390cb7c6e3d3623db4a2d334d266f9f3cfbc3f66b2924d181a168c01b71f8cc"

[versions]
fabric = "0.15.7"
minecraft = "1.20.2"
