name = "Manhunt+"
author = "XaNo11"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "57a19cff6f9ddb6254a196a33f3a1811e0c001e08d87415d47e2494d13cc61bc"

[versions]
fabric = "0.15.11"
minecraft = "1.20.2"
